FROM ubuntu:18.04

# 设置禁用交互
ARG DEBIAN_FRONTEND=noninteractive

# 设置容器时钟
ENV TZ=Asia/Shanghai

# 指定使用bash，-c表示后面命令是字符串
SHELL ["/bin/bash", "-c"]

# 删除所有已下载的软件包，位于/var/cache/apt/archives下面。apt-get autoclean删除的是旧版本的软件包，不包括最新版本
RUN apt-get clean

# 将本目录下的sources.list复制到容器的/etc/apt/ 目录下，里面包含了阿里镜像源，方便之后的软件安装
COPY sources.list /etc/apt/

# 安装必要的软件和库。
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    htop \
    apt-utils \
    curl \
    cmake \
    git \
    openssh-server \
    build-essential \
    qtbase5-dev \
    qtchooser \
    qt5-qmake \
    qtbase5-dev-tools \
    libboost-all-dev \
    net-tools \
    vim \
    stress \
    libc-ares-dev \
    libssl-dev \
    gcc \
    g++ \
    make \
    libx11-xcb1 \
    libfreetype6 \
    libdbus-1-3 \
    libfontconfig1 \
    libxkbcommon0 \
    libxkbcommon-x11-0 \
    python-dev \ 
    python3-dev \
    python-pip \
    python-all-dev \
    python3-pip

# 注意，COPY只能拷贝上下文目录下的文件，也就是docker build 命令的最后一个参数指定的目录
COPY install/abseil /tmp/install/abseil
RUN /tmp/install/abseil/install_abseil.sh

COPY install/cmake /tmp/install/cmake
RUN /tmp/install/cmake/install_cmake.sh

COPY install/protobuf /tmp/install/protobuf
RUN /tmp/install/protobuf/install_protobuf.sh

# 注意，最后安装grpc，因为对前面的有所依赖
COPY install/grpc /tmp/install/grpc
RUN /tmp/install/grpc/install_grpc.sh 

# 安装qt的一个简便python脚本
RUN pip3 install cuteci -i https://mirrors.aliyun.com/pypi/simple

COPY install/qt /tmp/install/qt
RUN /tmp/install/qt/install_qt.sh
